Repository googleapis/python-redis, pull requests merged in 2021-04, with the labels that each got.

#58 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: redis, automerge, cla: yes, context: full

#59 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: redis, cla: yes, context: full, samples

#62 chore: prevent normalization of semver versioning
  setup.py
Labels: api: redis, cla: yes

#61 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: redis, automerge, cla: yes, context: full

#63 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: redis, automerge, cla: yes

#64 chore(revert): revert preventing normalization
  setup.py
Labels: api: redis, cla: yes
